name: Lint HTML and SCSS

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint HTML and SCSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Lint Sass/SCSS com stylelint
        run: npx stylelint "**/*.scss"

      - name: Lint HTML com htmlhint
        run: npx htmlhint "**/*.html"
